# Generated by Django 2.2.1 on 2023-04-20 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('img', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='learn.Level'),
        ),
    ]
