# Generated by Django 2.2.1 on 2023-04-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20230420_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='level',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='learn.Level'),
        ),
    ]
