# Generated by Django 2.2.1 on 2023-04-18 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 18, 13, 58, 5, 251377)),
        ),
    ]
